- name: is k3s installed
  stat:
    path: /usr/local/bin/install-k3s.sh
  register: stat_result

- block:
  - name: install master
    shell: >
      export INSTALL_K3S_SKIP_DOWNLOAD=true && \
      /usr/local/bin/install-k3s.sh

  - name: cleanup
    file:
      path: /usr/local/bin/install-k3s.sh
      state: absent

  when: stat_result.stat.exists == True

- name: turn on k3s
  systemd:
    name: k3s
    enabled: yes
    state: started

- set_fact:
    master_token: "{{ lookup('file','/var/lib/rancher/k3s/server/node-token') }}"
